[CmdletBinding()] param([string]$GamePath,[switch]$VerifyOnly)
$ErrorActionPreference='Stop'
function Hash($p){$s=[IO.File]::OpenRead($p);$a=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($a.ComputeHash($s))).Replace('-','').ToLowerInvariant()}finally{$a.Dispose();$s.Dispose()}}
function Leaf($n){if([IO.Path]::GetFileName($n)-ne$n -or $n -notmatch '^[A-Za-z0-9_.-]+\.bundle$'){throw "Unsafe bundle name: $n"}}
function Exact($s,[int]$n){$b=New-Object byte[] $n;$o=0;while($o-lt$n){$r=$s.Read($b,$o,$n-$o);if($r-le 0){throw 'Truncated patch'};$o+=$r};$b}
function Patch($source,$patch,$out,$e){Copy-Item -LiteralPath $source -Destination $out;$ps=[IO.File]::OpenRead($patch);$r=[IO.BinaryReader]::new($ps);$os=$null;try{if([Text.Encoding]::ASCII.GetString($r.ReadBytes(6))-ne"F4KP1`0"){throw 'Bad patch magic'};$ss=$r.ReadUInt64();$ts=$r.ReadUInt64();$sh=([BitConverter]::ToString($r.ReadBytes(32))).Replace('-','').ToLowerInvariant();$th=([BitConverter]::ToString($r.ReadBytes(32))).Replace('-','').ToLowerInvariant();$bs=$r.ReadUInt32();$c=$r.ReadUInt32();if($ss-ne(Get-Item -LiteralPath $source).Length -or $sh-ne$e.source_sha256 -or $ts-ne$e.target_size -or $th-ne$e.target_sha256){throw "Patch metadata mismatch: $($e.bundle)"};$os=[IO.File]::Open($out,'Open','ReadWrite','None');$os.SetLength([int64]$ts);for($i=0;$i-lt$c;$i++){$off=$r.ReadUInt64();$rawn=$r.ReadUInt32();$cn=$r.ReadUInt32();if($rawn-gt$bs -or $off+$rawn-gt$ts){throw 'Invalid patch block'};$z=$r.ReadBytes($cn);if($z.Length-ne$cn){throw 'Truncated patch block'};$m=[IO.MemoryStream]::new($z,$false);$g=[IO.Compression.GZipStream]::new($m,[IO.Compression.CompressionMode]::Decompress);try{$raw=Exact $g $rawn}finally{$g.Dispose();$m.Dispose()};$os.Position=$off;$os.Write($raw,0,$raw.Length)}}finally{if($os){$os.Dispose()};$r.Dispose();$ps.Dispose()};if((Hash $out)-ne$e.target_sha256){throw "Patched hash mismatch: $($e.bundle)"}}
if(Get-Process -Name theFisher -ErrorAction SilentlyContinue){throw 'Fisher Online is running.'};if(-not $GamePath){throw 'Installer requires -GamePath.'}
$root=Split-Path -Parent $MyInvocation.MyCommand.Path;$manifest=Get-Content (Join-Path $root manifest.json) -Raw|ConvertFrom-Json;$game=(Resolve-Path -LiteralPath $GamePath).Path;$bundles=Join-Path $game 'theFisher_Data\StreamingAssets\aa\StandaloneWindows64';if(-not(Test-Path -LiteralPath $bundles)){throw 'Invalid game path.'}
foreach($e in $manifest.species){Leaf $e.bundle;$d=Join-Path $bundles $e.bundle;$p=Join-Path $root $e.patch;if(-not(Test-Path -LiteralPath $d)-or -not(Test-Path -LiteralPath $p)){throw "Missing game bundle or patch: $($e.bundle)"};if((Hash $p)-ne$e.patch_sha256){throw "Patch checksum failed: $($e.patch)"};$h=Hash $d;if($h-ne$e.target_sha256 -and $h-ne$e.source_sha256){throw "Unsupported game/mod state: $($e.bundle)"}}
if($VerifyOnly){Write-Host "All $($manifest.bundle_count) targets and patches passed preflight.";exit 0}
$stamp=Get-Date -Format yyyyMMdd-HHmmssfff;$backup=Join-Path $game "Mod Backups\FisherOnline-4K-Public-before-$stamp";New-Item -ItemType Directory $backup|Out-Null;$done=[Collections.Generic.List[object]]::new()
try{foreach($e in $manifest.species){$d=Join-Path $bundles $e.bundle;if((Hash $d)-eq$e.target_sha256){continue};Copy-Item -LiteralPath $d -Destination (Join-Path $backup $e.bundle);if((Hash (Join-Path $backup $e.bundle))-ne$e.source_sha256){throw "Backup verification failed: $($e.bundle)"}};foreach($e in $manifest.species){$d=Join-Path $bundles $e.bundle;if((Hash $d)-eq$e.target_sha256){continue};$tmp="$d.f4k-$stamp.tmp";$old="$d.f4k-$stamp.replace.bak";Patch $d (Join-Path $root $e.patch) $tmp $e;[IO.File]::Replace($tmp,$d,$old);$done.Add($e);if($env:F4K_TEST_FAIL_AFTER_REPLACE-eq$e.bundle){throw "Forced post-replace failure: $($e.bundle)"};if((Hash $d)-ne$e.target_sha256){throw "Installed hash mismatch: $($e.bundle)"};Remove-Item -LiteralPath $old -Force -ErrorAction SilentlyContinue;Write-Host "Installed: $($e.species)"}}catch{for($i=$done.Count-1;$i-ge 0;$i--){$e=$done[$i];Copy-Item -LiteralPath (Join-Path $backup $e.bundle) -Destination (Join-Path $bundles $e.bundle) -Force};throw}
@{status='installed_and_hash_verified';version=$manifest.version;installed_at=(Get-Date).ToString('o');backup=$backup;bundles=@($done|ForEach-Object{@{bundle=$_.bundle;source_sha256=$_.source_sha256;target_sha256=$_.target_sha256}})}|ConvertTo-Json -Depth 6|Set-Content (Join-Path $backup installation.json) -Encoding UTF8;Write-Host "Rollback backup: $backup"
